import * as stylex from "@stylexjs/stylex";
import { colors, radii, shadows, space, typography } from "@foldworks/ui/tokens.stylex";

export const styles = stylex.create({
  root: {
    width: "100%",
    height: "100svh",
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    color: colors.foreground,
    backgroundColor: colors.canvas,
  },
  toolbar: {
    flex: "0 0 auto",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
  },
  workspace: {
    flex: "1 1 auto",
    minHeight: 0,
    minWidth: 0,
    display: "grid",
    gridTemplateColumns: {
      default: "248px minmax(420px, 1fr) 340px",
      "@media (max-width: 1040px)": "220px minmax(360px, 1fr)",
      "@media (max-width: 720px)": "1fr",
    },
  },
  rail: {
    minWidth: 0,
    overflow: "auto",
    padding: space.md,
    borderRightWidth: "1px",
    borderRightStyle: "solid",
    borderRightColor: colors.border,
    backgroundColor: colors.surface,
  },
  railHeading: {
    margin: `0 0 ${space.md}`,
    color: colors.foregroundMuted,
    fontSize: typography.sizeXs,
    fontWeight: typography.weightSemibold,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  fileList: { display: "flex", flexDirection: "column", gap: space.xs },
  fileButton: {
    width: "100%",
    minWidth: 0,
    padding: `${space.sm} ${space.md}`,
    overflow: "hidden",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "transparent",
    borderRadius: radii.md,
    backgroundColor: { default: "transparent", ":hover": colors.surfaceHover },
    color: colors.foregroundMuted,
    cursor: "pointer",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: typography.sizeXs,
    textAlign: "left",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    outline: { default: "none", ":focus-visible": `2px solid ${colors.focus}` },
    outlineOffset: "2px",
  },
  activeFile: {
    borderColor: colors.selectionBorder,
    backgroundColor: colors.selection,
    color: colors.selectionForeground,
  },
  content: {
    minWidth: 0,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    padding: space.lg,
    gap: space.md,
  },
  documentHeading: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: space.md,
    minWidth: 0,
  },
  path: {
    overflow: "hidden",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: typography.sizeSm,
    fontWeight: typography.weightSemibold,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  editorFrame: {
    flex: "1 1 auto",
    minHeight: 0,
    display: "flex",
    overflow: "hidden",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radii.lg,
    backgroundColor: colors.surface,
    boxShadow: shadows.sm,
  },
  editor: {
    width: "100%",
    height: "100%",
    minHeight: "360px",
    resize: "none",
    borderWidth: 0,
    borderRadius: 0,
    padding: space.lg,
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: "13px",
    lineHeight: 1.65,
    tabSize: 2,
  },
  inspector: {
    minWidth: 0,
    overflow: "auto",
    padding: space.lg,
    borderLeftWidth: "1px",
    borderLeftStyle: "solid",
    borderLeftColor: colors.border,
    backgroundColor: colors.surface,
    display: { default: "block", "@media (max-width: 1040px)": "none" },
  },
  stack: { display: "flex", flexDirection: "column", gap: space.md },
  section: {
    padding: space.lg,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radii.lg,
    backgroundColor: colors.background,
  },
  sectionTitle: {
    margin: `0 0 ${space.sm}`,
    fontSize: typography.sizeSm,
    fontWeight: typography.weightSemibold,
  },
  muted: { color: colors.foregroundMuted, fontSize: typography.sizeSm, lineHeight: 1.55 },
  status: {
    flex: "0 0 auto",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: space.md,
    padding: `${space.sm} ${space.lg}`,
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: colors.border,
    backgroundColor: colors.surface,
    color: colors.foregroundMuted,
    fontSize: typography.sizeXs,
  },
  empty: {
    flex: "1 1 auto",
    display: "grid",
    placeItems: "center",
    color: colors.foregroundMuted,
    textAlign: "center",
  },
  srOnly: {
    position: "absolute",
    width: "1px",
    height: "1px",
    padding: 0,
    overflow: "hidden",
    clipPath: "inset(50%)",
    whiteSpace: "nowrap",
  },
});
