export {
  JsonDocumentCodec,
  YamlDocumentCodec,
  BuiltInDocumentCodecs,
  codecForFormat,
  codecForPath,
  formatForPath,
  parseDocument,
  stringifyDocument,
  parseYaml,
  decodeYamlEither,
} from "./document-codec";
export { summarizeDiagnostics, parseErrorToDiagnostics } from "./diagnostics";
export {
  Workspace,
  isWorkspaceSchema,
  type WorkspaceDecodeOptions,
  type WorkspaceRouteId,
  type WorkspaceRouteMap,
  type WorkspaceRoutes,
  type WorkspaceRouteValue,
  type WorkspaceSchema,
  type WorkspaceValidationIssue,
  type FileEntry,
} from "./workspace-schema";
export {
  createReflection,
  sourceTreeFromFiles,
  validateSchemaIdeValue,
  validateSingleDocument,
  type SchemaIdeInputSchema,
} from "./validation";
export {
  buildReferenceIndex,
  getSchemaIdeCompletions,
  getSchemaIdeDefinitions,
  getSchemaIdeHover,
  getSchemaIdeQuickFixes,
  getSchemaIdeReferences,
  type SchemaIdeCompletionItem,
  type SchemaIdeCompletionResult,
  type SchemaIdeDefinition,
  type SchemaIdeHover,
  type SchemaIdeQuickFix,
  type SchemaIdeReference,
  type SchemaIdeWorkspaceTextEdit,
} from "./schema-language-service";
export {
  createEmptyFS,
  deleteFile,
  listFiles,
  normalizePath,
  readFile,
  sourceFilesToVirtualFs,
  virtualFsToSourceTree,
  writeFile,
  type VirtualFile,
  type VirtualFSState,
} from "./virtual-fs";
export { createMemorySourceRepository, type SourceRepository } from "./source-repository";
export {
  applyWorkspaceChange,
  canRedoWorkspaceChange,
  canUndoWorkspaceChange,
  checkoutWorkspaceRevision,
  createVersionedWorkspace,
  getCurrentWorkspaceRevision,
  getWorkspacePatchPaths,
  redoWorkspaceChange,
  undoWorkspaceChange,
  type VersionedWorkspaceState,
  type WorkspaceChange,
  type WorkspacePatch,
  type WorkspaceRevision,
  type WorkspaceRevisionActor,
  type WorkspaceRevisionMetadata,
} from "./workspace-history";
export {
  compareWorkspaceBranches,
  compareWorkspaceFiles,
  createWorkspaceBranch,
  detectWorkspaceBranchConflicts,
  mergeWorkspaceBranch,
  mergeWorkspaceFiles,
  type CompareWorkspaceBranchesInput,
  type CreateWorkspaceBranchInput,
  type MergeWorkspaceBranchInput,
  type MergeWorkspaceFilesInput,
  type WorkspaceBranchComparison,
  type WorkspaceBranchKind,
  type WorkspaceBranchMergeResult,
  type WorkspaceBranchMergeStrategy,
  type WorkspaceBranchMetadata,
  type WorkspaceBranchState,
  type WorkspaceFileDiff,
  type WorkspaceFilesMergeResult,
  type WorkspaceMergeConflict,
  type WorkspaceMergeConflictType,
} from "./workspace-branches";
export type {
  AnySchema,
  ReflectedSchema,
  RouteMatch,
  SchemaIdeDiagnostic,
  SchemaIdeDiagnosticSource,
  SchemaIdeDocumentCodec,
  SchemaIdeDocumentFormat,
  SchemaIdeParseFailure,
  SchemaIdeParseResult,
  SchemaIdeParseSuccess,
  SchemaIdeReflection,
  SchemaIdeValidationSummary,
  SourceFile,
  SourceTree,
  ValidationResult,
} from "./types";
